version: '3.8'

services:
  api:
    build: ./api
    command: gunicorn --bind 0.0.0.0:5000 --timeout 400 --log-level debug app:app
    volumes: 
    - ./api:/home/app
    - ./logs:/home/app/logs
    ports:
    - 5000:5000
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"
        labels: "app=flask-app"


  # nginx:
  #   build: ./services/nginx
  #   environment:
  #     - VIRTUAL_HOST=your_domain
  #     - LETSENCRYPT_HOST=your_domain
  #   ports:
  #     - 80:80
  #     - 443:443
  #   depends_on:
  #     - api
  #   restart: always
